openface:
  build: .
  volumes:
    - ./openface/train.py:/root/openface/vampart/train.py
    - ./data.json:/root/openface/vampart/data.json
    - ./storage:/root/openface/vampart/storage
  ports:
    - "1337:1337"
