version: '2'
services:
  openface:
    build: ./openface
    working_dir: /root/openface/vampart
    command: python api.py
    volumes:
      - ./openface/core.py:/root/openface/vampart/core.py
      - ./openface/train.py:/root/openface/vampart/train.py
      - ./openface/api.py:/root/openface/vampart/api.py
      - ./data.json:/root/openface/vampart/data.json
      - ./storage:/root/openface/vampart/storage
      - ./public/uploads/images:/root/openface/vampart/public/uploads/images
      - ./public/landing-page-image.jpeg:/root/openface/vampart/public/landing-page-image.jpeg
    ports:
      - "1337:1337"
