default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password:

development:
  <<: *default
  database: vampart_development

test:
  <<: *default
  database: vampart_test

production:
  adapter: postgresql
  encoding: unicode
  database: vampart_production
  pool: 5
  username: vampart
  password: <%= ENV['VAMPART_DATABASE_PASSWORD'] %>
